# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=70)),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('circuit_overseer', models.CharField(blank=True, max_length=40, null=True)),
                ('circuit', models.CharField(blank=True, max_length=40, null=True)),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
                ('access_key', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
