# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregation',
            name='added_by',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
